name: build

on:

 push:
   tags:
     - '*'
     
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-24.04

  steps:

    - name: checkout main
      uses: actions/checkout@v4
      with:
        path: main
        
    - name: checkout svg-cursor
      uses: actions/checkout@v4
      with:
        repository: jinliu/svg-cursor
        path: svg-cursor


    - name: get-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y inkscape python3 x11-apps python3-cairosvg

    - name: build-xcursor
      run: |
        cd /home/runner/work/WhiteSur-cursors/WhiteSur-cursors/main
        ./build.sh

    - name: build-svgcursor
      run: |
        cd /home/runner/work/WhiteSur-cursors/WhiteSur-cursors/main
        ../svg-cursor/build-svg-theme/build-svg-theme.py --output-dir=dist/cursors_scalable --svg-dir=src/svg --config-dir=src/config --alias-file=src/cursorList --nominal-size=24

    - uses: actions/upload-artifact@v4
      with:
        name: WhiteSur-cursors
        path: /home/runner/work/WhiteSur-cursors/WhiteSur-cursors/dist/
  
