name: build

on:

 push:
   tags:
     - '*'
     
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-24.04

  steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        sudo apt-get update
        sudo apt-get install -y inkscape python3 x11-apps python3-cairosvg
        cd WhiteSur-cursors
        ./build.sh
