name: build

on:
 push:
 workflow_dispatch:

env:
  NOMINAL_SIZE: 24

jobs:
 build:
  runs-on: ubuntu-24.04

  steps:

    - name: checkout main
      uses: actions/checkout@v4
      with:
        path: main
        
    - name: checkout svg-cursor
      uses: actions/checkout@v4
      with:
        repository: jinliu/svg-cursor
        path: svg-cursor

    - name: speed up apt
      run: |
        sudo mkdir -p /etc/dpkg/dpkg.cfg.d
        sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc <<'EOF'
        path-exclude=/usr/share/locale/*;
        path-exclude=/usr/share/man/*;
        path-exclude=/usr/share/doc/*;
        path-include=/usr/share/doc/*/copyright;
        EOF
        sudo chmod 644 /etc/dpkg/dpkg.cfg.d/01_nodoc

    - name: setup
      working-directory: ${{ github.workspace }}/main
      run: |
        rm -rf dist
        mkdir dist
        sudo apt-get update
        cat apt-packages.txt | xargs -r sudo apt-get install --no-install-recommends -y

    - name: build x cursors
      working-directory: ${{ github.workspace }}/main
      run: ./build.sh

    - name: build svg cursors
      working-directory: ${{ github.workspace }}/main
      run: |
        ../svg-cursor/build-svg-theme/build-svg-theme.py --output-dir=dist/cursors_scalable --svg-dir=src/svg --config-dir=src/config --alias-file=src/cursorList --nominal-size=${{ env.NOMINAL_SIZE }}

    - name: Package artifacts for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tar czf ${{ github.event.repository.name }}.tar.gz -C ${{ github.workspace }}/main/dist/ .

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.run_number }}
        path: ${{ github.workspace }}/main/dist/{{ github.event.repository.name }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ github.workspace }}/main/dist/{{ github.event.repository.name }}.tar.gz
        tag_name: ${{ github.ref_name }}
        name:  ${{ github.event.repository.name }} ${{ github.ref_name }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
