name: build

on:

 push:
   tags:
     - '*'
     
 workflow_dispatch:


env:
  NOMINAL_SIZE: 24

jobs:
 build:
  runs-on: ubuntu-24.04

  steps:

    - name: checkout main
      uses: actions/checkout@v4
      with:
        path: main
        
    - name: checkout svg-cursor
      uses: actions/checkout@v4
      with:
        repository: jinliu/svg-cursor
        path: svg-cursor


    - name: setup
      run: |
        sudo apt-get update
        sudo apt-get install -y inkscape python3 x11-apps python3-cairosvg
        rm -rf ${{ github.workspace }}/main/dist
        mkdir -p ${{ github.workspace }}/main/dist

    - name: build x cursors
      working-directory: ${{ github.workspace }}/main
      run: ./build.sh

    - name: build svg cursors
      working-directory: ${{ github.workspace }}/main
      run: |
        ../svg-cursor/build-svg-theme/build-svg-theme.py --output-dir=dist/cursors_scalable --svg-dir=src/svg --config-dir=src/config --alias-file=src/cursorList --nominal-size=${{ env.NOMINAL_SIZE }}

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-${{ github.run_number }}
        path: ${{ github.workspace }}/main/dist/

    - name: Package artifacts for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tar czf ${{ github.event.repository.name }}.tar.gz -C ${{ github.workspace }}/main/dist/ .

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ github.workspace }}/main/dist/{{ github.event.repository.name }}.tar.gz
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
